### ISSUE TITLE
[REQUEST] We need a README. Here the info i got from reddit:

### ISSUE THREAD

**Issue by loddi-o** [Koriebonx98/Main-Stuff#2]
https://www.reddit.com/r/PiratedGames/comments/1giunuj/comment/lv9g8ga/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

From the creator.

Doesn’t add games to steam but does for playnite.

Download addon and place in extension folder.

Set up “Games” and “Repacks” folders on your drives. And we’ll playnite will do rest

“D:/Games/Skate 4” gets added as “Skate 4” and all exe as play actions,

If “D:/Repacks/Skate 4 [Repack]” gets added as uninstall but makes a “install” button

If game is in both it inc the “install” action

**Comment by Koriebonx98** [comment]
> https://www.reddit.com/r/PiratedGames/comments/1giunuj/comment/lv9g8ga/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> 
> From the creator.
> 
> Doesn’t add games to steam but does for playnite.
> 
> Download addon and place in extension folder.
> 
> Set up “Games” and “Repacks” folders on your drives. And we’ll playnite will do rest
> 
> “D:/Games/Skate 4” gets added as “Skate 4” and all exe as play actions,
> 
> If “D:/Repacks/Skate 4 [Repack]” gets added as uninstall but makes a “install” button
> 
> If game is in both it inc the “install” action

i was the one who put on reddit. made new guide on reddit too
