### ISSUE TITLE
First of all great work i love it, it was working well but suddendly stopped woking any ideas is there a log i can check

### ISSUE THREAD

**Issue by sentix001** [Koriebonx98/Main-Stuff#3]
Also suggestion for the exlusions, ncan you add an option if there is a folder .egstore for epic games it excludes them as well

**Comment by Koriebonx98** [comment]
Can you please further explain the problem? So I can see what prob is, also there should be log in playnite folder I belive it’s “extensions.log”

And for the second thing, I’ll try but I found just keeping any epic games in a diff folder like “D:/Epic/“ and then any cracked games in “Games” sorts the situation

**Comment by sentix001** [comment]
it used to import games automatically in the games folders now its stopped, the other games via steam etc work well emulators as well
[extensions.zip](https://github.com/user-attachments/files/18222495/extensions.zip)

**Comment by sentix001** [comment]
the last one it imported correctly was talos principle 2

**Comment by Koriebonx98** [comment]
Can’t find what the error could be.

what did you do since last use addon (working) did you install any extensions ect?

I recommend, close playnite, del all logs. Then update local pc games and it should just display that data instead of all extensions

**Comment by sentix001** [comment]
Ok so here what it was, finally figured it out the error was in playnite.log not extensions.log

there was a broken symbolic link (i use it to move stuff around without breaking shorcuts) which was breaking the whole system

Now cleared woking back fine thanks for your time :)

**Comment by Koriebonx98** [comment]
> Ok so here what it was, finally figured it out the error was in playnite.log not extensions.log
> 
> there was a broken symbolic link (i use it to move stuff around without breaking shorcuts) which was breaking the whole system
> 
> Now cleared woking back fine thanks for your time :)

Brilliant, thanks for the feed back. I’m in the works atm of a new addon if you would be interested in trialing it? 

Add me on discord: “koriebonx98”

**Comment by Koriebonx98** [comment]
Issue fixed

**Comment by sentix001** [comment]
Added

**Comment by Koriebonx98** [comment]
> Also suggestion for the exlusions, ncan you add an option if there is a folder .egstore for epic games it excludes them as well

Just seen this suggestion, have you tried adding to exclusions list. Del old games then update lib? This should work hopefully
